dbt_garmin_transformation:
  outputs:
    dev:
      dbname: 
      host: localhost
      pass: ''
      port: 5432
      schema: analytics
      threads: 1
      type: postgres
      user: postgres
  target: dev
